# image: registry.gitlab.com/pages/hugo/hugo_extended:latest

stages:
  - deploy

# pages:
#   script:
#   - hugo
#   artifacts:
#     paths:
#     - public
#   rules:
#   - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  image: node:lts

  before_script:
    - cd astro
    - npm ci

  script:
    - npm run build
    - pwd
    - ls -la
    - mkdir ${CI_PROJECT_DIR}/public
    - cp -r dist/* ${CI_PROJECT_DIR}/public

  artifacts:
    paths:
      - public
  only:
    - astro