image: rust:latest

variables:
  COBALT_VERSION: "v0.18.3"
  COBALT_GIT_URL: https://github.com/cobalt-org/cobalt.rs.git
pages:
  script:
  - git clone --branch $COBALT_VERSION $COBALT_GIT_URL
  - cd cobalt.rs/
  - cargo build --release
  - export PATH="$PATH:$(pwd)/target/release/"
  - cobalt --version
  - cd ../
  - ls -la 
  - cobalt build -d public
  - ls -la 
  artifacts:
    paths:
    - public/
  only:
  - main