image: debian:latest

variables:
  COBALT_VERSION: "v0.15.0"
pages:
  script:
  - apt-get update && apt-get -y install curl
  - curl -LSfs https://japaric.github.io/trust/install.sh |
    sh -s --
    --git cobalt-org/cobalt.rs
    --crate cobalt
    --force
    --target x86_64-unknown-linux-gnu
    --tag $COBALT_VERSION
  - export PATH="$PATH:~/.cargo/bin"
  - cobalt build -d public
  - ls -la public
  - ls -la public/public
  artifacts:
    paths:
    - public/
  only:
  - main