name: Build an Publish to GCP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22.x
      uses: actions/setup-node@v3
      with:
        node-version: 22.x
    
    - name: Build
      run: |
        npm install
        npm run build

    - name: GCP Auth
      uses: 'google-github-actions/auth@v2'
      with:
        service_account: 'github-runner-blog-publisher-s@gcp-almaz-murzabekov-net.iam.gserviceaccount.com'
        credentials_json: '${{ secrets.GCP_SECRET }}'

    - name: Upload to Cloud Storage
      uses: 'google-github-actions/upload-cloud-storage@v2'
      with:
        path: 'dist/'
        destination: 'almaz.murzabekov.net'
        parent: false
